package com.deploypilot.provider.model;

/**
 * Request to create a database project. {@code plan} is always the free tier in
 * this stage — a paid plan is never selected automatically. {@code dbPassword}
 * is generated by the caller, used transiently to create the project, and is
 * never logged or stored in run outputs.
 */
public record DatabaseProjectRequest(
    String organizationId,
    String name,
    String region,
    String plan,
    String dbPassword
) {
    /** Paid plans are never auto-selected; the free tier is always requested. */
    public static final String FREE_PLAN = "free";
}
